create a form controller
ComeHomeAI/chai-form pull request #78
Opened 2024-10-30 18:42 UTC by MostafaIsmaiel

input state handler
inputs style handler
form style handler

2024-11-03 20:52 UTC, MostafaIsmaiel commented
add code snippets components
add more variables
add reset functionality

2024-11-04 09:55 UTC, MostafaIsmaiel commented
Add header and button text attributes to chai-form and implement input handling

2024-11-21 03:29 UTC, LarsKemmann requested changes
I've flagged a couple of significant functionality issues in the PR. The live editing experience works pretty well overall, but the items I flagged prevent me from accepting this.

2024-11-21 03:29 UTC, LarsKemmann commented on src/chai-form.ts
The formatting changes to this file make it very difficult to review accurately.

2024-11-21 03:29 UTC, LarsKemmann commented on src/chai-form.ts
> +    // );
Why did you comment out this existing functionality? You broke the form's behavior. 😲

2024-11-21 03:29 UTC, LarsKemmann commented on src/ChaiFormState.ts
> +export interface ChaiFormState {
You missed the `<chai-date>` field.

2024-11-21 03:29 UTC, LarsKemmann commented on src/chai-CopyCode.ts
> +          <button @click=${this.copyToClipboard}>Copy CSS Variables</button>
The `<style>` and `<chai-form>` should be separate; one usually goes in the website header, while the other goes wherever it needs to on the page.

2024-11-21 03:29 UTC, LarsKemmann commented on src/chai-general-form-panel.ts
> +  private handleHeaderTextChange(value: string) {
The header text is one example of a value that doesn't get reset properly when clicking "Reset Values"; if I clear it out, the displayed form actually uses the blank value (even though the blank value isn't shown in the HTML snippet), so the default header value isn't shown.

2024-11-27 12:51 UTC, MostafaIsmaiel commented
Reset chai-form.ts to default component
add chai-date component to state handler component
separate styles and html to two difference text area
Fix reset values for panels

2024-12-08 18:48 UTC, merged

2024-12-08 19:01 UTC, LarsKemmann commented
Continuing this conversation in #91

2024-12-08 19:07 UTC, LarsKemmann commented
> Note to self, @MostafaIsmaiel, & @WhiteHatTux -- I didn't mean to actually merge this just now, that was a mistake (since this PR breaks the build and isn't production-ready). I'm reverting the branch history on _main_ to clean that up. However, I am going to use this as a draft to spec out what the actual form editor should look like. 😊

Looks like the broken build in #91 was just a fluke. So, now it's just a matter of specifying what we want the final production UI to look like, as well as some coding standards and code quality updates. I'll work on that over the next two weeks.

@MostafaIsmaiel Thank you for your efforts here!