Continuously save manual address input
ComeHomeAI/chai-form pull request #85
Opened 2024-11-20 02:13 UTC by WhiteHatTux

If an autocomplete address is chosen it will be the last request and the autocomplete option will be stored in the backend.

If no autocomplete option was chosen the last entered manual address will be chosen.

2024-11-20 02:13 UTC, WhiteHatTux commented
Also introduced the change to restrict addresses to the US for now.

2024-11-20 22:18 UTC, LarsKemmann requested changes

2024-11-20 22:18 UTC, LarsKemmann commented on src/chai-address.ts
I think there's currently a bug whereby, if the user selects a Google autocomplete suggestion and then reloads the page, the saved address will not be shown. Can you please take a look at fixing that? Feels important enough to include (I'd think it's a matter of saving the formatted address into local storage along with the place ID, i.e. saving both whenever a place ID is selected, and displaying the formatted address when loading the initial value and finding it to be a place ID). Along the same lines, if I run the form locally but without the server, my interim edits are also not being saved; that's a potentially-related issue to fix as well. (It works for other fields, just not address)

2024-11-21 16:29 UTC, WhiteHatTux commented on src/chai-address.ts
I thought I had missed something, but actually this doesn't currently work in production either. 
I can fix it for the manual address, but resolving the placeid from storage to a display-address is not straight-forward. Some typescript issue doesn't seem to allow accessing the API directly and I don't want to introduce a new lib for this.

2024-11-22 02:57 UTC, LarsKemmann approved these changes

2024-11-22 03:11 UTC, merged